# Generated by Django 3.0.5 on 2021-05-10 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('types', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SizeType',
            fields=[
                ('sizes', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ToppingType',
            fields=[
                ('toppings', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SizeType')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ToppingType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PizzaType')),
            ],
        ),
    ]
