# Generated by Django 3.0.5 on 2021-05-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'Pizza'},
        ),
        migrations.AlterModelOptions(
            name='pizzatype',
            options={'verbose_name_plural': 'PizzaType'},
        ),
        migrations.AlterModelOptions(
            name='sizetype',
            options={'verbose_name_plural': 'SizeType'},
        ),
        migrations.AlterModelOptions(
            name='toppingtype',
            options={'verbose_name_plural': 'ToppingType'},
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(to='app.ToppingType'),
        ),
    ]
